---
env:
  es6: true
  jest: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
plugins:
  - prettier
globals:
  Atomics: readable
  SharedArrayBuffer: readable
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  import/no-extraneous-dependencies:
    - 2
    - devDependencies: true
  sort-keys: 2
